export const ELEMENTS = {
    registrationForm: '.shop-menu > .nav > :nth-child(4) > a',
    signUpEmail: '[data-qa="signup-email"]',
    signUpName: '[data-qa="signup-name"]',
    signUpBtn: '[data-qa="signup-button"]',
    genderTitle: '#id_gender2',
    password: '[data-qa="password"]',
    dayOfBirth: '[data-qa="days"]',
    monthOfBirth: '[data-qa="months"]',
    yearOfBirth: '[data-qa="years"]',
    newsletter: '#newsletter',
    specialOffers: '#optin',
    firstName: '[data-qa="first_name"]',
    lastName: '[data-qa="last_name"]',
    company: '[data-qa="company"]',
    address: '[data-qa="address"]',
    secondAddress: '[data-qa="address2"]',
    country: '[data-qa="country"]',
    state: '[data-qa="state"]',
    city: '[data-qa="city"]',
    zipCode: '[data-qa="zipcode"]',
    mobileNumber: '[data-qa="mobile_number"]'
}